# Production Web Crawler Configuration
# Optimized for Render deployment with 0.5 vCPU and 512MB RAM

# Resource Constraints
max_memory_mb: 450  # Leave 62MB buffer from 512MB limit
max_cpu_percent: 60.0
initial_concurrency: 10
max_concurrency: 20
min_concurrency: 5

# Request Settings
request_timeout: 30
max_content_length: 1048576  # 1MB max page size
user_agent: "MusicCrawler/1.0 (+https://github.com/musiccrawler)"

# Politeness Settings
default_delay: 1.0  # 1 RPS per host
robots_cache_ttl: 3600  # Cache robots.txt for 1 hour
max_pages_per_domain: 1000
max_depth: 5

# Storage Configuration
# These will be overridden by environment variables in production
redis_url: "redis://localhost:6379"
postgres_url: "postgresql://localhost/crawler"

# Output Settings
output_dir: "./output"
log_level: "INFO"

# Target Domains for Music Crawling
target_domains:
  # Lyrics & Chord Sites
  - "ultimate-guitar.com"
  - "azchords.com"
  - "e-chords.com"
  - "chordie.com"
  - "songsterr.com"
  - "chordify.com"
  - "azlyrics.com"
  
  # Independent Music Platforms
  - "bandcamp.com"
  - "soundcloud.com"
  - "reverbnation.com"
  - "audiomack.com"
  
  # Music Discovery & Reviews
  - "last.fm"
  - "discogs.com"
  - "musicbrainz.org"
  - "pitchfork.com"
  - "allmusic.com"
  - "rateyourmusic.com"
  
  # Music Equipment & Gear
  - "reverb.com"
  - "sweetwater.com"
  
  # Chart & Analytics
  - "billboard.com"

# Crawler Behavior Settings
crawl_policies:
  # Hybrid roaming configuration
  priority_crawl_ratio: 0.7  # 70% priority targets, 30% exploration
  exploration_depth: 3
  
  # Domain-specific limits
  domain_limits:
    "ultimate-guitar.com": 2000
    "bandcamp.com": 1500
    "last.fm": 1000
    "discogs.com": 1000
  
  # Content type preferences
  allowed_content_types:
    - "text/html"
    - "application/xhtml+xml"
  
  # Skip patterns
  skip_patterns:
    - "*/ads/*"
    - "*/admin/*"
    - "*/login/*"
    - "*/register/*"
    - "*.pdf"
    - "*.zip"
    - "*.exe"

# Scaling Configuration
scaling:
  memory_warning_threshold: 0.85  # 85% of max memory
  memory_critical_threshold: 0.95  # 95% of max memory
  cpu_warning_threshold: 0.85     # 85% of max CPU
  
  # Concurrency adjustment steps
  scale_up_step: 2
  scale_down_step: 2
  
  # Health check intervals
  health_check_interval: 30  # seconds
  resource_cleanup_interval: 100  # pages